-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;

CREATE TABLE Category (
    id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    category_name VARCHAR(30) NOT NULL
);

CREATE TABLE Product (
    id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    product_name VARCHAR(30) NOT NULL,
    price DECIMAL (10,2) NOT NULL,
    stock INTEGER NOT NULL,
    category_id INTEGER
)

CREATE TABLE Tag (
    id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    tag_name VARCHAR(30)
)

CREATE TABLE ProductTag (
    id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    product_id INTEGER,
    tag_id INTEGER
)